/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fta_bsdiff_Bsdiff */

#ifndef _Included_com_fta_bsdiff_Bsdiff
#define _Included_com_fta_bsdiff_Bsdiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fta_bsdiff_Bsdiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fta_bsdiff_Bsdiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fta_bsdiff_Bsdiff
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fta_bsdiff_Bsdiff_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
